server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/department_service_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

